### PR TITLE
Rp2040

### PR DESCRIPTION
**Pull request by runger1101001**
RP2040 aka Raspberry Pico support.

3PWM and 6PWM, tests are ongoing.

### CODE REVIEW

**Comment by runger1101001** [comment]
Hmmm... I was actually hoping to put this into a new branch...

**Comment by askuric** [comment]
Very nice!
Do we include this in the v2.1.1 or we leave it for the next one?

**Comment by askuric** [comment]
For windows users, change of driver needed in some cases.
https://arduino-pico.readthedocs.io/en/latest/install.html#uploading-sketches

**Comment by askuric** [comment]
FYI.  3PWM and 6PWM work out of the box for me, well done! ;D

**Comment by runger1101001** [comment]
Hey, I think it could be merged, especially if you tested it :-)

**Comment by askuric** [comment]
Ok, I am in. It's probably good that it goes out so that we have a bit feedback :D
I'll update the docs about the `Pullu`p change and add the Pico support.

**Comment by askuric** [comment]
Just a quick info, since it is a bit related to this PR. I've had to change the `Pullup` enum once again since `EXTRENAL` is deffined for Aruidnos :D

So now the enum is;
```cpp
 enum Pullup{
    USE_INTERN, //!< Use internal pullups
    USE_EXTERN //!< Use external pullups
};

```

**Pull request merged**
