### PR TITLE
Refactoring PID code

### PR DESCRIPTION
**Pull request by cousinitt**
I thought that it might be neat to add some smarts to the PID structure - to make it a functor. This would allow us to pull out some of the PID logic from the BLDCMotor class, and perhaps reuse it elsewhere as well.

If this is something that you think is an improvement, I could also do something similar with the low-pass filter.

Since this isn't really user-facing (i.e. in the "ino" file) it won't hurt/help understanding for most users of the library.

(as always - no hurt feelings if you don't like, I can close to clean up the PR part of your page).

### CODE REVIEW

**Comment by cousinitt** [comment]
I should either get/build one of the shields and try this out on an actual motor ... it isn't so much of a work in progress, but rather something that is adapted from something else I was working on.

Should I close this one as well (I didn't look at the new code you had for the library yet)?

**Comment by askuric** [comment]
This one is included also yes. 
Both are in the dev branch

**Comment by owennewo** [comment]
@cousinitt and @askuric - I've just looked at dev, you guys have been busy!

I like what i see. Thankyou both!

Looking forward to 1.6 release.

**Comment by cousinitt** [comment]
Ah - neat, it is already in devel branch! I'll cancel this PR.

**Pull request closed without merging**
