### PR TITLE
Add clang format

### PR DESCRIPTION
**Pull request by KaSroka**
Add clang-format support as discussed in #84.

This includes code reformatting to conform with proposed formatting as well as github action to check this. The only downside is that this action doesn't check `.ino` files, I haven't figured out how to check them.

### CODE REVIEW

**Comment by runger1101001** [comment]
Hey, that's cool, thank you for this work!

I must leave it to @askuric  to decide this - it changes *all* the files. Normally we don't accept changes that modify too much of the code, but perhaps this is a special case.

Just so you understand our hesitancy, please keep in mind that sweeping changes to the code mean someone has to test things. And we support:

- ATMega
- ESP32
- STM32
- RP2040
- SAMD21/51
- Teensy
- Due

- SPI Sensors
- I2C Sensors
- Enoders
- Hall Sensors
- Current Sensing

- BLDC Motors
- Stepper Motors

So sweeping changes mean someone has to physically test a very large number of hardware combinations to ensure we haven't broken anything... for this reason we need to be a bit careful.

But we really appreciate the effort you are putting in! Thank you!!

**Comment by KaSroka** [comment]
I fully understand it! It's always up to maintainers to accept or decline PR.

**Comment by KaSroka** [comment]
Also from testing perspective - it's not changing logic in code but only formatting so compilation check + review looking for unnecessary changes should be sufficient.

**Comment by askuric** [comment]
Hey @KaSroka, as you can see we are very hesitant to merge this kind of PRs to the main library. There are many changes and we are do not have a specific formatting style that we want to settle for the moment. :D
Thanks for the proposition, but I prefer not to include it to the library at the moment.

**Pull request closed without merging**
