### PR TITLE
add MT6701 I2C sensor configuration

### PR DESCRIPTION
**Pull request by alperbasarn**

### CODE REVIEW

**Comment by runger1101001** [comment]
Thanks a lot for this contribution!

I will gladly merge it, but we accept the PRs only against the dev branch of the library. I've changed the base of your PR, but there are some other parallel changes. I'll look into this, and merge it once I've sorted this out.

**Comment by alperbasarn** [comment]
thanks! let me know if you would like me to rebase and resolve if there are any conflicts.

**Comment by runger1101001** [comment]
Hey, if you do not mind sending it again based on the "dev" branch then I could straight merge it.

It's not your fault, we caused this by accidentally merging some changes to the master branch.
I've tried to fix it by pre-merging the changes from the master branch but it hasn't worked as I expected, and I still see your PR as including the other changes.

Can I ask you to rebase your changes on the dev branch, then I can merge that.
Otherwise, if you prefer I can rebase your changes locally, this will be no work for you, but it might lose the reference to your GitHub user and contribution.

**Comment by alperbasarn** [comment]
Sure thing, I have also extended example file for demonstrating MT6701 integration.

But, somehow I cannot see dev branch in my fork, and cannot push a proposal branch to direct clone(not forked). is there any permission that needs to be granted ?

**Comment by runger1101001** [comment]
> But, somehow I cannot see dev branch in my fork, and cannot push a proposal branch to direct clone(not forked). is there any permission that needs to be granted ?

Huh, that's weird... I'm not sure. Maybe there is a way to pull over the other branch into your forked repo on GitHub but not sure how...

One way you could definately do it is to add the SimpleFOC repo as another remote to your local cloned copy, and then pull the dev branch from this. Then you can push that branch to your fork, and do the PR from there...

**Pull request closed without merging**
